### PR TITLE
Protocol 11 Fixes  ~~~  All Credit goes to @Luka967

### PR DESCRIPTION
**Pull request by Tyler3D**

### CODE REVIEW

**Comment by Shair17** [comment]
This fix LeaderBoard?

**Comment by Tyler3D** [comment]
yep

**Comment by Shair17** [comment]
Yessss :D Thanks Tyler3D i love you

**Comment by Tyler3D** [comment]
You got to thank @Luka967 xD

**Comment by Shair17** [comment]
Thanks Luka ;D

**Comment by Luka967** [comment]
xD

**Pull request merged**
